apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "loadrun-k6.fullname" . }}-m
  labels:
    app: myapp
  {{- include "loadrun-k6.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: m-http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      group: zerok-demoapp