apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-k6-with-vars
spec:
  parallelism: 4
  arguments:  -o experimental-prometheus-rw
  # cleanup: post
  script:
    configMap:
      name: loadtestscripts
      file: status.js
  initializer:
    env:
      - name: "K6_INCLUDE_SYSTEM_ENV_VARS"  # this enables environment variables for the initializer
        value: "1"
      
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: 'http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write'
      - name: STAGES
        value: "2m_10000-3m_10000"
      - name: VUS
        value: "9000" 
      - name: START_RATE 
        value: "10000"