apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    app: myapp
    dep: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      dep: default
  template:
    metadata:
      labels:
        app: myapp
        dep: default
    spec:
      nodeSelector: {
        cloud.google.com/gke-nodepool: load-workers
      }
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "k6"
        effect: "NoSchedule"
      containers:
        - name: k6-load-generator
          image: us-west1-docker.pkg.dev/zerok-dev/zk-client/devclient03/zk-load-test:latest
          imagePullPolicy: Always
          ports:
          - name: m-http
            containerPort: 8000
          resources: 
            requests: 
              cpu: 1000m
              memory: 4500Mi
            limits:
              cpu: 1850m
              memory: 5000Mi 