#prettier-ignore
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  status.js: |-
{{ .Files.Get "status.js" | indent 4 }}
  inventory.js: |-
{{ .Files.Get "inventory.js" | indent 4 }}